In [2]:
class Employee:
    class_name = 'Employee'

    # double underscore -> dunder
    def __init__(self, id, name):
        self.id = id
        self.name = name

    def __str__(self):
        return f"{self.id} with name {self.name}"
    
    def __repr__(self):
        return f"{self.name} has the id {self.id}"

employee = Employee(2596, "Kirk")
print(employee)
employee

2596 with name Kirk


Kirk has the id 2596

In [3]:
employee.class_name

'Employee'

In [2]:
import numpy as np

a = np.array((1,2,3,4), dtype=np.int16)
b = [1,2,3,4]

a[0] = 111
a

array([111,   2,   3,   4], dtype=int16)

In [3]:
a = np.array((1,2,3,4), dtype=np.int16)
b = [1,2,3,4]

x = a[1:3]
y = b[1:3]

x[0] = 22
y[0] = 22

print(a, b)

[ 1 22  3  4] [1, 2, 3, 4]


In [11]:
mat = np.array(([1,2,3],[4,5,6]), dtype=np.int32)
print(mat.shape) # row, col
print(mat.ndim)
print(mat.size)
print(mat.dtype)

(2, 3)
2
6
int32


In [13]:
a = np.zeros((2,3,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [33]:
b = np.ones(10)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
c = np.empty(5)
c

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [ ]:
ab = np.arange(1, 11, 2) #excluding 11
ab

array([1, 3, 5, 7, 9])

In [ ]:
bc = np.linspace(20, 100, 9) # start 20 ; end 100; points 9
print(bc)   # 9 points -- 8 gaps; 80/8 = 10 elements

[ 20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [4]:
data = np.array([1, 2, 3, 4, 5, 6]) # 1D array of size 6 [cite: 195]
new_matrix = data.reshape(2, 3)     # Converts into a 2x3 matrix layout [cite: 196]
print(new_matrix)

[[1 2 3]
 [4 5 6]]


In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 4, 8], [9, 10, 11, 12]])

# 1. Evaluate the condition array
mask = a < 5 
# This generates a boolean matrix of the same shape filled with True/False values

# 2. Apply mask as index coordinates
print(a[mask]) 
# Output: [1, 2, 3, 4] [cite: 214]

[1 2 3 4 4]


In [9]:
filtered = a[(a > 2) & (a < 11)] 
# Output: [ 3,  4,  5,  6,  7,  8,  9, 10] [cite: 218]
print(filtered)

[ 3  4  5  6  4  8  9 10]


In [11]:
data = np.array([1, 2]) 
ones = np.array([1, 1]) 
print(data + ones) # Output: [2, 3] [cite: 270, 272, 274]

[2 3]


In [ ]:
data = np.array([1.0, 2.0]) 
print(data * 1.6) # Output: [1.6, 3.2] scalar brodacasting

var1 = np.array([4,5,6,8,9,7,10])
var2=np.array([10])
print(var1+var2)  # diff dimension ops only possible if one has only 1 value; scalar to vector

[1.6 3.2]
[14 15 16 18 19 17 20]


In [17]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix.max(axis=0))
print(matrix.max(axis=1))
print(matrix.min(axis=0))
print(matrix.min(axis=1))

[3 4]
[2 4]
[1 2]
[1 3]


In [ ]:
# ca = np.random.random(10)
ca = np.random.uniform(0, 10, (2,3))
print(ca)

In [20]:
a = np.random.random(10)
print(a)

# a = np.sort(a)
a.sort()
print(a)

[0.67255595 0.77766311 0.33840663 0.89828654 0.09257007 0.31691451
 0.18013364 0.27952251 0.67985661 0.9742794 ]
[0.09257007 0.18013364 0.27952251 0.31691451 0.33840663 0.67255595
 0.67985661 0.77766311 0.89828654 0.9742794 ]


In [ ]:
a = np.random.random((2,3))
b = np.random.random((2,4))
print(a, b)

c = np.vstack((a,b))
print(c)

d = np.hstack((a,b))
print(d)

In [24]:
a = np.random.random(6)
print(a)
b = np.split(a,3)
print(b)

[0.60957799 0.14526048 0.90085981 0.87786973 0.31843142 0.35518243]
[array([0.60957799, 0.14526048]), array([0.90085981, 0.87786973]), array([0.31843142, 0.35518243])]


In [ ]:
a = np.random.random((4,4))
b = np.random.random((4,1))
print(a)
print(b)
a + b

In [ ]:
a = np.random.random((2,3))
print(a)
a.max(axis=1)

# axis 0 downward
# axis 1 towards right

In [18]:
np.exp

<ufunc 'exp'>